/* NavAuiShim */
(function(E){E.execute(function(){(function(e){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!e.$Nav)e.$Nav=a("rcx-nav");if(!e.$Nav.make)e.$Nav.make=a})(window)})})(function(){var E=window.AmazonUIPageJS||P,e=E.attributeErrors;return e?e("NavAuiShim"):E}());
;/* RetailSearchAutocompleteAssets */
(function(D){D.execute(function(){window.$Nav.when("$","nav.inline").run(function(d){window.$Nav.declare("config.blackbelt",d("#nav-belt").length>0)});window.$Nav.when("config.blackbelt").run(function(d){d?window.$Nav.when("searchApi").run(function(c){window.$Nav.declare("sxSearchApi",c)}):window.$Nav.declare("sxSearchApi")});window.$Nav.when("$","sxSearchApi","sx.iss.DomUtils").build("NavDomApi",function(d,c,b){var e,a,f;function i(){return l?j().find('input[type="text"]'):(typeof k==="undefined"&&
(k=d(e)),k)}function h(){return l?c.flyout.elem():(typeof t==="undefined"&&(t=d(r),j().after(t)),t)}function g(){return l?c.options().parents("select"):(typeof u==="undefined"&&(u=d(a)),u)}function j(){return l?c.options().parents("form"):d(f)}function m(){var a=p(),b=h();h().is(":visible")&&!(b.html().length<1)&&b.css({left:a.offset().left,width:a.width()})}function p(){q===void 0&&(q=d("#nav-iss-attach"));return q}var l=c!==void 0;e="#twotabsearchtextbox";a="#searchDropdownBox";f="#nav-searchbar";
var k,n,t,u,q,r='<div id="search-dropdown" class="search-dropdown"></div>',o=/search-alias\s*=\s*([\w-]+)/;c===void 0&&d(window).resize(m);return{getAliasDropdown:g,getSearchBox:i,getSearchBoxId:function(){return e},getSearcchSuggestions:function(){typeof n==="undefined"&&(n=d("#srch_sggst"));return n},getKeyword:function(){var a;a=c!==void 0?c:i();return b.getKeyword(a)},setKeyword:function(a){if(c!==void 0)c.val(a);else return i().val(a)},getAliasFromDropdown:function(){var a=g().val();return(a=
a&&a.match(o))?a[1]:void 0},getCategoryNameFromDropdown:function(a){var b="";a?(a=g().find('option[value$="search-alias='+a+'"]'),b=a.length>0?d(a[0]).text():b):b=g().find("option:selected").text();return d.trim(b)},getDropdown:h,showDropdown:function(a){l?(typeof a!=="undefined"&&c.flyout.elem().html(a),c.flyout.show()):(typeof a!=="undefined"&&h().hide().html(a),a=p(),h().css({left:a.offset().left,width:a.width()}).show())},hideDropdown:function(){l?c.flyout.hide():h().hide()},getOption:function(a){if(!a)return g().find("option:selected");
a=g().find('option[value$="search-alias='+a+'"]');return a.length>0?d(a[0]):d()},getForm:j,getIssPrefixElem:function(){return d("#issprefix")},getSuggestions:function(){return d(".s-suggestion")},submitForm:function(){j().submit()},getOriginalSearchTerm:function(){return j().data("originalSearchTerm")},getOriginalAlias:function(){return j().data("originalAlias")},isSearchBoxFocused:function(){return i().get(0)===document.activeElement},activateSearchBox:function(){j().addClass("nav-active")},deactivateSearchBox:function(){j().removeClass("nav-active")},
getSearchApi:function(){return c}}});window.$Nav.build("sx.iss.TemplateEngine",function(){var d={};return function b(e,a){var f=/^[a-zA-Z0-9_-]+$/.test(e)?d[e]=d[e]||b(document.getElementById(e).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+e.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");
return a?f(a):f}});window.$Nav.when("$").build("sx.iss.TemplateInstaller",function(d){function c(b,c){var a=document.createElement("script");a.setAttribute("type","text/html");a.setAttribute("id",b);a.text=c;return a}d("body");return{init:function(){var b=document.createDocumentFragment();b.appendChild(c("s-suggestion",'<div id="<#= suggestionId #>"class="s-suggestion"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-isSc="<#= isSpellCorrected #>"data-isFb="<#= isFallback #>"data-type="<#= type #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #><# if (typeof storeHtml === "string") { #> <#= storeHtml #><# } #></div>'));
b.appendChild(c("suggestions-template",'<div id="suggestions-template"><# if (typeof suggestionTitle !== "undefined") { #><div id="suggestion-title"><#= suggestionTitle #></div><# } #><div id="suggestions"><# if (typeof suggestions !== "undefined") {for(var i=0; i < suggestions.length; i++) {var displayString = suggestions[i].display; #><#= displayString #><# }} #></div></div>'));b.appendChild(c("s-separator",'<div id="s-separator"><div class="s-separator"></div></div>'));b.appendChild(c("s-department",
'<div id="<#= suggestionId #>" class="s-suggestion s-highlight-primary"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-type="<#= type #>">Shop the <#= beforePrefix #><span class="s-heavy"><#= prefix #></span><#= suffix #> store</div>'));b.appendChild(c("s-option",'<option value="<#= value #>"><#= store #></option>'));b.appendChild(c("s-minimal",'<div class="s-suggestion s-custom" data-url="<#= url #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));
b.appendChild(c("s-storeText",'<span class="<#= cssClasses #>"><#= store #></span>'));b.appendChild(c("s-corpus",'<div class="s-suggestion" id="<#= suggestionId #>"data-alias="<#= alias #>"data-url="<#= url #>"data-type="<#= type #>"data-keyword="<#= keyword #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));document.body.appendChild(b)}}});window.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(d,c){return new function(){function b(a){var b=
typeof a,c="";b==="object"&&a.hasOwnProperty("name")?c=a.name:b==="string"&&(c=a);return c}var e={},a={};this.listen=function(a,i,h){var g,j="";if(c.isArray(a)){for(g=0;g<a.length;g++)j=a[g],this.listen(j,i,h),d.logDebug("Listening for: "+j);return this}j=b(a);e[j]||(e[j]=[]);e[j].push({f:i,o:h});d.logDebug("Listening for: "+j);return this};this.trigger=function(a,c){var h=b(a);d.logDebugWithTrace("Trigger: "+h,c);var h=e[h],g;if(h){for(g=0;g<h.length;g++)h[g].f.call(h[g].o,c);return this}};this.triggerThrottledEvent=
function(c,i,h){var g=b(c);d.logDebugWithTrace("Trigger (throttled): "+g,i);var j=e[g],c=a[g];if(j)return h===void 0&&(h=100),c&&(clearTimeout(c),delete a[g]),c=setTimeout(function(){var b;for(b=0;b<j.length;b++)j[b].f.call(j[b].o,i);delete a[g]},h),a[g]=c,this}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi","sx.iss.DebugUtils").build("sx.iss.PublicApi",function(d,c,b,e,a){function f(a){e.getSearchBox().focus(a)}function i(a){a===void 0?e.getSearchBox().blur():e.getSearchBox().blur(a)}
var h=/node\s*=\s*([\d]+)/,g=/bbn\s*=\s*([\d]+)/,j=/^me=([0-9A-Z]*)/,m=/^\s+/,p=/\s+/g;return{searchAlias:function(){return e.getAliasFromDropdown()},searchNode:function(){var a=e.getAliasDropdown().val().match(h);return a?a[1]:null},bbn:function(){var a=e.getAliasDropdown().val().match(g);return a?a[1]:null},merchant:function(){var a=e.getAliasDropdown().val().match(j);return a?a[1]:null},encoding:function(){var a=e.getForm().find('input[name^="__mk_"]');if(a.length)return[a.attr("name"),a.val()]},
keyword:function(){return e.getSearchBox().val().replace(m,"").replace(p," ")},submit:function(b){a.logDebugWithTrace("Attaching the submit event handler to the form...");e.getForm().submit(b)},suggest:function(a){c.eventBus.listen(b.globals.suggestionsRendered,function(b){var c=[];d.each(b.suggestions,function(a,b){b.type!=="separator"&&c.push(b)});a(b.searchTerm,c)})},onFocus:f,onBlur:i,focus:f,blur:i,isImeEnhUsed:function(){return!1},keydown:function(a){var b="#"+e.getSearchBox().attr("id");e.getForm().delegate(b,
"keydown",a)}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils").build("sx.iss.Weblab",function(d,c,b){return function(d,a){function f(a){d.hasOwnProperty(a)&&(d[a](),b.logDebug("Triggering: "+a+" weblabs"))}c.eventBus.listen(a.keydown,function(){f("doCTWKeydown")});c.eventBus.listen(a.suggestionsRendered,function(){f("doCTWDisplay")})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","NavDomApi","sx.iss.ReftagBuilder","sx.iss.DebugUtils").build("sx.iss.Reftag",function(d,c,
b,e,a,f){return function(b,d,g){function j(b){return(new a).build(b,g.hasOwnProperty("shouldAddImeTag")&&g.shouldAddImeTag())}function m(b){if(b.suggestions===void 0||b.searchTerm===void 0)f.logDebug('"suggestions" or "searchTerm" is undefined',b);else{for(var c=a.CONSTANTS.noSearchTermMatchInResults,d=b.searchTerm,b=b.suggestions,e=0;e<b.length;e++)if(d===b[e].keyword){c=a.CONSTANTS.searchTermMatchInResults;break}k(c)}}function p(){k(a.CONSTANTS.noResults)}function l(a){a.suggestion===void 0||a.searchTerm===
void 0?f.logDebug('"suggestion" or "searchTerm" is undefined',a):k(j(a))}function k(b){var c=/(ref=[\-\w]+)/,d=/(dd_[a-z]{3,4})(_|$)[\w]*/,f=e.getForm(),g=f.attr("action");c.test(g)?g=d.test(g)?g.replace(d,"$1_"+b):g.replace(c,a.CONSTANTS.reftagBase+b):(g.charAt(g.length-1)!=="/"&&(g+="/"),g+=b);f.attr("action",g)}d===void 0&&(d={});g===void 0&&(g={});c.eventBus.listen(b.selectionChange,l);c.eventBus.listen(b.suggestionsRendered,m);c.eventBus.listen(b.noSuggestions,p);return{create:j,updateReftagAfterRender:m,
updateReftagAfterSelection:l,updateReftagAfterNoSuggestions:p,updateFormActionWithReftag:k}}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.DataAttributes","NavDomApi","sx.iss.DebugUtils").build("sx.iss.ReftagBuilder",function(d,c,b,e,a,f){function i(){function c(a){a!==void 0&&l.push(a);return this}function i(b){var b=a.getOption(b.data("alias")).val(),c=b.indexOf("=");if(c===-1)return"";var b=b.substr(c+1),c=b.indexOf("-"),d=b.substr(0,3);return c?d:d+b.charAt(c+1)}function m(d,
n){var m=d.suggestion,u=d.searchTerm,q=d.previousSearchTerm;f.isDebugModeOn()&&f.logDebugWithTrace("Build reftag for search term: "+u+" pre term:"+q,m);a.getSuggestions();var r=p(m),o=r.reftag;c(h.base);n&&c(h.ime);var s;if(m.data(e.fallback.name)===!0)s=h.fallback;else if(m.data(e.spellCorrected.name)===!0)s=h.spellCorrected;s!==void 0?c(s):(m.data("type")===b.department.name&&(c(b.a9Xcat.reftag),c(m.data("alias"))),c(o));o!==b.a9.reftag&&o!==b.a9Corpus.reftag?c(0):(r=r.name,r=a.getDropdown().find('.s-suggestion[data-type="'+
r+'"]').index(m)+1,c(r));m===void 0?(c(h.undefinedSugg),m=i(m),c(m)):c(q?q.length:u.length);return l.join(h.separator)}function p(a){var c=b.a9;d.each(b,function(b,d){if(a.data("type")===d.name)return c=d,!1});return c}function i(a){var a=a.val(),b=a.indexOf("=");if(a!==""||b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-")+1,c=a.substr(0,3);return b?c:c+a.charAt(b)}var l=[];return{build:m,buildFull:function(a,b){return h.reftagBase+m(a,b)}}}var h={base:"ss",fallback:"fb",spellCorrected:"sc",undefinedSugg:"dd",
reftagBase:"ref=nb_sb_",noResults:"noss",searchTermMatchInResults:"noss_1",noSearchTermMatchInResults:"noss_2",ime:"ime",separator:"_"};i.CONSTANTS=h;return i});window.$Nav.when("NavDomApi","sx.iss.DebugUtils").build("sx.iss.suggestionUtils",function(d,c){function b(a){var b;typeof d.getAliasFromDropdown()==="undefined"&&a&&(b=a.searchAliasAccessor());return b}var e=/\s/;return{getPrefixPos:function(a,b){return a.toLowerCase().indexOf(b.toLowerCase())},getPrefixPosMultiWord:function(a,b){var c=a.toLowerCase().indexOf(b.toLowerCase()),
d;if(c===-1)return-1;if(c===0)return 0;d=a[c-1];return d===" "||d==="\t"||d.match(e)?c:-1},splitStringForDisplay:function(a,b,c){return{bprefix:a.substr(0,b),prefix:a.substr(b,c),suffix:a.substr(b+c)}},getDeepNodeAlias:b,getDeepNodeCategoryName:function(a,b){var c;a&&(c=d.getCategoryNameFromDropdown(a)||b.searchAliasDisplayNameAccessor());return c},shouldRequestSuggestions:function(a,f){var e;if((a==="department"||a==="a9")&&f.hasOwnProperty("aliases")){var h=d.getAliasFromDropdown()||b(f.deepNodeISS);
e=f.aliases==="*"||f.aliases.indexOf(h)>-1;c.logDebug("Should we request suggestions for: alias : "+h+" provider : "+a+"? "+e);return e}return!0}}});window.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance","sx.iss.suggestionUtils","sx.iss.DependenciesMet").build("sx.iss.utils",function(d,c,b){return{timingProvider:d,eventBus:c,suggestionUtils:b,now:function(){return(new Date).getTime()},escapeRegExp:function(b){return b.replace(/([.*+?\^${}()|\[\]\/\\])/g,"\\$1")}}});window.$Nav.when("$").build("sx.iss.DomUtils",
function(){var d=/\+/g,c=/^\s+/;(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,c){var a=this.length>>>0,d=Number(c)||0,d=d<0?Math.ceil(d):Math.floor(d);for(d<0&&(d+=a);d<a;d++)if(d in this&&this[d]===b)return d;return-1}})();return{isHoveredClass:"is-hovered",getKeyword:function(b){return(b=b.val())?b.replace(c,""):b},isElHoveredOver:function(b){return b.hasClass("is-hovered")},hoverOverEl:function(b){return b.addClass("is-hovered")},hoverOutEl:function(b){return b.removeClass("is-hovered")},
isArray:function(b){return Object.prototype.toString.call(b)==="[object Array]"},getFormParams:function(b){for(var b=b.split("?"),c=b.length>1?b[1]:void 0,c=c?c.split("&"):[],a=c.length,f;a-- >0;)f=c[a].split("="),c[a]={name:f[0],value:f[1].replace(d," ")};return{uri:b[0],formParams:c}},suggestionClass:".s-suggestion",hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(b){return b.find(".is-hovered").length>0},getCursorPosition:function(b){b=b.get(0);
if("selectionStart"in b)return b.selectionStart;else if(document.selection){b.focus();var c=document.selection.createRange(),a=c.text.length;c.moveStart("character",-b.value.length);return c.text.length-a}return-1}}});window.$Nav.build("sx.iss.DebugUtils",function(){function d(b){if(b&&b.length>0)for(var b=b.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==="debug"){for(var e in a)a.hasOwnProperty(e)&&(a[e]=d[1].indexOf(e)!==-1?!0:!1);break}}}function c(){return a.iss||a.isstrace}
function b(){return a.isstrace}function e(a,b){c()&&window.console&&(b!==void 0?console.debug(a,b):console.debug(a))}var a={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1,isscf:!1};d(window.location.search);return{init:d,logDebug:e,logDebugWithTrace:function(a,c){e(a,c);b()&&console.trace()},isDebugModeOn:c,isDebugModeOnWithTrace:b,isDisableISS:function(){return a.noiss},isUsingPolyFill:function(){return a.isspolyfill},isQIAEnabled:function(){return a.isscf}}});window.$Nav.build("sx.iss.ObjectUtils",
function(){return{freeze:function(d){Object.freeze&&d&&Object.freeze(d)}}});window.$Nav.when("$","sx.iss.DebugUtils").run(function(d,c){c.isDisableISS()||((!d.fn.delegate||c.isUsingPolyFill())&&d.extend(d.fn,{delegate:function(b,e,a){return this.bind(e,function(f){var e=d(f.target);if(e.is(b)||e.parents(b).length>0)return c.logDebug("delegate ",{selector:b,target:e,event:f}),a.apply(e,arguments)})}}),window.$Nav.declare("sx.iss.DependenciesMet"))});window.$Nav.when("sx.iss.DepartmentDataFormatter").build("sx.iss.DepartmentData",
function(d){var c=[["instant-video","Amazon Instant Video",["Amazon","Instant","Video","movies","rentals"]],["appliances","Appliances",["Appliances"]],["mobile-apps","Apps for Android",["Apps","Android","mobile"]],["arts-crafts","Arts, Crafts & Sewing",["arts","crafts","sewing"]],["automotive","Automotive",["automotive","cars"]],["baby-products","Baby Products",["baby","products"]],["beauty","Beauty",["beauty","makeup","hair"]],["stripbooks","Books",["books","textbooks","rentals"]],["mobile","Cell Phones & Accessories",
"cell,phones,mobile,cases,iphone,galaxy,nexus".split(",")],["collectibles","Collectibles & Fine Art",["collectibles","fine","art"]],["computers","Computers",["computers","pc","laptop","desktop"]],["electronics","Electronics",["electronics"]],["financial","Credit Cards",["credit","cards"]],["gift-cards","Gift Cards Store",["gift","cards"]],["grocery","Grocery & Gourmet Food",["grocery","gourmet","food"]],["hpc","Health & Personal Care",["health","personal","care"]],["garden","Home & Kitchen",["home",
"kitchen","furniture","art"]],["industrial","Industrial & Scientific",["Industrial","Scientific"]],["digital-text","Kindle Store",["kindle","store","ebooks"]],["magazines","Magazine Subscriptions",["magazines","subscriptions"]],["movies-tv","Movies & TV","movies,tv,dvds,vhs,video,blu ray,bluray,blu-ray".split(",")],["digital-music","MP3 Music",["mp3","music"]],["popular","Music",["music","cds","autorip","vinyl"]],["mi","Musical Instruments",["musical","instruments","guitars","dj"]],["office-products",
"Office Products",["office","products","school","toner"]],["lawngarden","Patio, Lawn & Garden",["patio","lawn","garden"]],["pets","Pet Supplies","pet,supplies,dogs,cats,birds,fish".split(",")],["software","Software",["software"]],["sporting","Sporting & Outdoors",["sporting","outdoors","sports"]],["tools","Tools & Home Improvement",["tools","home","improvement"]],["toys-and-games","Toys & Games",["toys","games"]],["videogames","Video Games","video,games,xbox,ps3,ps4,wii,playstation".split(",")],["wine",
"Wine",["wine"]],["pantry","Prime Pantry",["prime","pantry"]]],b=[["fashion","Clothing, Shoes & Jewelry","clothing,clothes,luggage,hats,shirts,jacket,wallets,sunglasses,jewelry,shoes,handbags,sandals,boots,watches".split(",")],["fashion-mens","Men's Clothing, Shoes & Jewelry","mens,clothing,clothes,shoes,jewelry,mens clothing,mens shoes,mens jewelry,watches,mens watches".split(",")],["fashion-womens","Women's Clothing, Shoes & Jewelry","womens,clothing,clothes,shoes,jewelry,womens clothing,womens shoes,womens jewelry,watches,womens watches".split(",")],
["fashion-baby","Baby Clothing, Shoes & Jewelry","baby,clothing,clothes,shoes,jewelry,baby clothing,baby shoes,baby jewelry".split(",")],["fashion-boys","Boys Clothing, Shoes & Jewelry","boys,clothing,clothes,shoes,jewelry,boys clothing,boys shoes,boys jewelry".split(",")],["fashion-girls","Girls' Clothing, Shoes & Jewelry","girls,clothing,clothes,shoes,jewelry,girls clothing,girls shoes,girls jewelry".split(",")]],e=[["jewelry","Jewelry",["jewelry"]],["shoes","Shoes",["shoes","handbags","sandals",
"boots"]],["apparel","Clothing & Accessories","clothing,clothes,hats,shirts,jacket,wallets,sunglasses".split(",")]];return{getData:function(a){var f=c,a=typeof a!=="undefined"&&a.hasOwnProperty("isWayfindingEnabled")&&a.isWayfindingEnabled===1?b:e,f=f.concat(a);return d.format(f)}}});window.$Nav.build("sx.iss.DepartmentDataFormatter",function(){return{format:function(d){for(var c=[],b=0;b<d.length;b++){var e=d[b];c.push({id:e[0],alias:e[0],keyword:"",type:"department",store:e[1],name:"",triggerWords:e[2],
sn:!1})}return c}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(d){var c={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},a9XOnly:{name:"a9-xcat-only",reftag:"xo",source:"xo",templateId:"s-suggestion"},a9Corpus:{name:"a9-corpus",reftag:"cp",reftagTemplate:"REF_TAG",templateId:"s-corpus"},department:{name:"department",reftag:"deptiss",templateId:"s-department"}};d.freeze(c);return c});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.InfoTypes",
function(d){var c={actor:"actor",author:"author",director:"director",seasonTitle:"season_title",title:"title"};d.freeze(c);return c});window.$Nav.build("sx.iss.DataAttributes",function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});window.$Nav.build("sx.iss.TimingEvents",function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});window.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",function(d){function c(){var b=Date.now();return{uid:b,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+
b},suggestionsReady:{name:"suggestionsReady-"+b},suggestionsRendered:{name:"suggestionsRendered-"+b},updateSearchBox:{name:"updateSearchBox-"+b},selectionChange:{name:"selectionChange-"+b},dropdownHidden:{name:"dropdownHidden-"+b},updateSearchTerm:{name:"updateSearchTerm-"+b},suggestionClicked:{name:"suggestionClicked-"+b},suggestionsNeeded:{name:"suggestionsNeeded-"+b},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+b},noSuggestions:{name:"nosuggestions-"+b},searchBoxFocusIn:{name:"searchBoxFocusIn-"+
b},searchBoxFocusOut:{name:"searchBoxFocusOut-"+b},keydown:{name:"keydown-"+b},hideDropdown:{name:"hidedropdown-"+b}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"}},createInstance:function(){return new c},createEvent:function(b,c){var a=c;c.hasOwnProperty("name")?a=c.name:typeof c==="string"?a=c:d.logDebug('Format of "event" parameter is not a string or an event object',c);return b+"-"+a}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",
function(d){var c={name:"desktop",cid:"amazon-search-ui",callback:"String",needExtraParams:!0};d.freeze(c);return c});window.$Nav.when("$").build("sx.iss.TimingProvider.instance",function(d){return new function(){var c={};this.startTimer=function(b,d){c[b]||(c[b]={});c[b][d]={start:+new Date}};this.stopTimer=function(b,d){var a=c[b]&&c[b][d];if(!a)return-1;a.end=+new Date;return a.end-a.start};this.getTimings=function(b){return c[b]};this.getTimingStats=function(b){var e={name:b},a=0,f=0,i=void 0,
h=void 0,g=0,j=0,m=[],p=0,l=0;if(c[b]){d.each(c[b],function(a,b){if(b.start&&b.end){j=b.end-b.start;m.push(j);g++;f+=j;if(!i||j<i)i=j;if(!h||j>h)h=j}});m.sort();e.n=g;e.avg=f/g;e.min=i;e.max=h;e.med=g===1?m[0]:g%2?(m[Math.floor(g/2)]+m[Math.ceil(g/2)])/2:m[g/2];for(a=0;a<g;a++)p=m[a]-e.avg,p*=p,l+=p;e.stddev=Math.sqrt(l/g);return e}};this.getTimingWithDisplayLatency=function(b,d){var a=c[b]&&c[b][d];return!a?-1:a.end-a.start+100}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.Events",
"sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.A9SuggestionQueryConstructors","sx.iss.A9SuggestionResultsProcessors","sx.iss.DebugUtils").build("sx.iss.A9SuggestionProvider",function(d,c,b,e,a,f,i,h,g){var j="a9",m=f.a9;return function(a,l,k){function n(a,b){var h=++u,i,n;q=document.getElementsByTagName("head").item(0);r="JscriptId"+h;o=document.createElement("script");o.setAttribute("type","text/javascript");o.setAttribute("charset","utf-8");o.setAttribute("src",b);o.setAttribute("id",r);o.onload=
o.onreadystatechange=function(){if(!(i||this.readyState!==void 0&&this.readyState!=="loaded"&&this.readyState!=="complete")){i=!0;if(completion!=="undefined"){var b=t(),l=!b||d.inArray(b,w)===-1?f.a9:f.a9Corpus;n=x.getResultsProcessor(l.name).processResults(a,b,completion)}this.onload=this.onreadystatechange=null;try{q.removeChild(o)}catch(s){g.logDebug(s)}c.timingProvider.stopTimer(j,h);b={searchTerm:a,suggestionSets:n};l=e.createEvent(j,k.suggestionsReady);c.eventBus.trigger(l,b)}};c.timingProvider.startTimer(j,
h);q.appendChild(o)}function t(){var a="aps",a=[],a=l.aliases;(a=l.implicitAlias?[l.implicitAlias]:typeof a==="string"?a.split(","):a)&&a.length===1?a=a[0]:(a=b.getAliasFromDropdown(),typeof a==="undefined"&&(a=c.suggestionUtils.getDeepNodeAlias(l.deepNodeISS)));return a}var u=0,q,r,o,s=new i(l),x=new h(l),w=l.issCorpus||[];c.eventBus.listen(k.a9SuggestionsNeeded,function(a){if(c.suggestionUtils.shouldRequestSuggestions(j,l))if(!a||!a.length){var a={searchTerm:a,suggestions:[]},b=e.createEvent(j,
k.suggestionsReady);c.eventBus.trigger(b,a)}else{var b=t(),g=!b||d.inArray(b,w)===-1?f.a9:f.a9Corpus;(b=s.getUrlConstructor(g.name).constructUrl(a,b))&&n.call(this,a,b)}},this);return{getName:function(){return j},processResults:x.getResultsProcessor(m.name).processResults}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.Platform","sx.iss.DebugUtils").build("sx.iss.A9SuggestionQueryConstructors",function(d,c,b,e,a,f,i){return function(h){function g(a){return{constructUrl:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+
a+" when asking for query constructors");return""}}}function j(a){var c=e.getCursorPosition(b.getSearchBox());return c>-1?{q:encodeURIComponent(d.trim(a.substring(0,c))),qs:encodeURIComponent(a.substring(c))}:{q:encodeURIComponent(a)}}function m(a){var b="?";d.each(a,function(a,c){b+=a+"="+c+"&"});return b}function p(){var a={xcat:h.xcat,cf:h.cf,noCacheIE:c.now()};if(h.fb!==void 0)a.fb=h.fb;if(h.np!==void 0)a.np=h.np;a.sc=1;return a}var l=h.protocol||window.parent.document.location.protocol||"http:";
l==="file:"&&(l="http:");var k={};k[a.a9.name]=new function(){var a=l+"//"+h.src,b={method:"completion",mkt:h.mkt,client:f.cid,x:f.callback};return{constructUrl:function(c,e){var g=d.extend({},b,{"search-alias":e},j(c));f.needExtraParams&&d.extend(g,p());return a+m(g)}}};k[a.a9Corpus.name]=new function(){var a=l+"//"+h.src.replace("/search","/v2.0"),b={"num-corpus":5,"num-query":0,client:f.cid,m:h.obfMkt,fb:1,xcat:0,method:"completion",cf:0,sc:1,conf:1,x:f.callback};return{constructUrl:function(c,
f){var e=d.extend({},b,{"search-alias":f},j(c));return a+m(e)}}};return{getUrlConstructor:function(a){return k.hasOwnProperty(a)?k[a]:new g(a)}}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.InfoTypes","sx.iss.DebugUtils").build("sx.iss.A9SuggestionResultsProcessors",function(d,c,b,e,a,f,i){return function(d){function g(a){return{processResults:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for result processing");
return""}}}var j={};j[a.a9.name]=new function(){function f(c,e){var g={type:c.type,bprefix:c.bprefix,prefix:c.prefix,suffix:c.suffix,keyword:c.keyword,alias:c.alias||e,isSpellCorrected:c.isSpellCorrected,isFallback:c.isFallback,isDeepNode:c.isDeepNode},i;if(g.type===a.a9Xcat.name||g.type===a.a9XOnly.name||g.isDeepNode===!0){if(c.isFirst||!d.noXcats)c.store?i=c.store:c.isFirst&&(i=b.getCategoryNameFromDropdown())}else i=void 0;g.store=i;i=g.alias;var j="/s?k="+encodeURIComponent(c.keyword);typeof i!==
void 0&&(j+="&i="+encodeURIComponent(i));g.url=j;return g}var g=a.a9.name;return{processResults:function(i,k,n){var j=n[1],u=n.length>2?n[2]:[],q=0,n=[],r=[],o,s,x;x=!1;for(var w=0;w<u.length;w++){var y=u[w];if(y.hasOwnProperty("source"))for(var y=y.source,v=0;v<y.length;v++)if(y[v]==="fb"){x=!0;break}}w=!1;for(y=0;y<u.length;y++)if(v=u[y],v.hasOwnProperty("nodes")&&v.nodes.length>0){w=!0;break}if(y=d.hasOwnProperty("cf"))if(y=d.cf){y=!1;for(v=0;v<u.length;v++){var B=u[v];if(B.hasOwnProperty("nodes")&&
B.nodes.length>0&&B.hasOwnProperty("source")&&e.isArray(B.source)&&B.source[0]==="xo"){y=!0;break}}}d.deepNodeISS&&(o=c.suggestionUtils.getDeepNodeAlias(d.deepNodeISS),s=c.suggestionUtils.getDeepNodeCategoryName(o,d.deepNodeISS));for(v=0;v<j.length;v++){var B=o,z=s,A=i,C=j[v],F=v,D=u&&u[F]&&u[F].sc==="1",I=c.suggestionUtils.getPrefixPos(C,A),G=void 0,H=void 0,E=void 0,E=void 0;D||I===-1?(G=C,H=E=""):(E=c.suggestionUtils.splitStringForDisplay(C,I,A.length),G=E.bprefix,H=E.prefix,E=E.suffix);B={type:g,
isSpellCorrected:D,bprefix:G,prefix:H,suffix:E,keyword:C,isFirst:F===0,alias:B,store:z,isDeepNode:B!==void 0&&z!==void 0};if(!x&&!(v===0&&y))if(A=n,z=B,C=k,v===0&&typeof o==="undefined"&&w){A=r;z.isFirst=!1;z.type=a.a9Xcat.name;C=b.getAliasFromDropdown();if(C!=="aps")z.store=b.getCategoryNameFromDropdown(C),z.alias=C,A.push(f(z,void 0));z.store=b.getCategoryNameFromDropdown("aps");z.alias="aps";A.push(f(z))}else A.push(f(z,C));if(!d.noXcats){z=(A=u[v])&&A.source&&A.source[0]==="fb";A=A.nodes||[];
for(C=0;C<A.length&&q<4;C++)F=A[C],D=y,I=z,B.store=F.name,B.alias=F.alias,B.type=D?a.a9XOnly.name:a.a9Xcat.name,B.isFallback=I,r.push(f(B,k)),q++}}i={};i[a.a9.name]=n;i[y?a.a9XOnly.name:a.a9Xcat.name]=r;return i}}};j[a.a9Corpus.name]=new function(){var b=a.a9Corpus;return{processResults:function(d,e,g){var h=[],g=g.suggs;if(g.length===0)return h;for(var i=0;i<g.length;i++){var j=g[i];if(!(j.hasOwnProperty("conf")&&j.conf<80)){var q=j.corpus,r;r=j.source;for(var o=[],s=0;s<r.length;s++)o.push(r[s].field);
r=o;for(o=0;o<q.length&&h.length<5;o++){var s=q[o],x;x=j;for(var w=s.asin_info,y=r,v="",B=0;B<w.length;B++){var z=w[B],A=z.type,z=z.value;if(A===f.title||A===f.seasonTitle)v+=z[0];y.indexOf(A)>=0&&z.indexOf(x.sugg)>=0&&(A===f.actor?v+=", starring "+x.sugg:A===f.director&&(v+=", directed by "+x.sugg))}x=v;w=c.suggestionUtils.getPrefixPos(x,d);w===-1?(w=x,y=v=""):(v=c.suggestionUtils.splitStringForDisplay(x,w,d.length),w=v.bprefix,y=v.prefix,v=v.suffix);h.push({text:x,url:"/dp/"+s.asin+"/"+a.a9Corpus.reftagTemplate+
"?keywords="+x,type:b.name,keyword:x,alias:e,bprefix:w,prefix:y,suffix:v})}}}d={};d[a.a9Corpus.name]=h;return d}}};return{getResultsProcessor:function(a){return j.hasOwnProperty(a)?j[a]:new g(a)}}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DepartmentData","NavDomApi","sx.iss.Events").build("sx.iss.DepartmentSuggestionProvider",function(d,c,b,e,a){function f(f,m){function p(l){if(c.suggestionUtils.shouldRequestSuggestions(i,f)){var k={searchTerm:l,suggestionSets:{}},n=[],p=RegExp("\\b"+c.escapeRegExp(l)+
"(.*)","i");if(l.length>=h&&e.getKeyword().length===l.length){var u,q,r,o;d.each(b.getData(f),function(a,b){o=r=q="";if(p.test(b.triggerWords)||p.test(b.store)){b.position=n.length===0?0:n.length+1;var d=c.suggestionUtils.getPrefixPos(b.store,l);d===-1?o=b.store:(u=c.suggestionUtils.splitStringForDisplay(b.store,d,l.length),q=u.bprefix,r=u.prefix,o=u.suffix);b.beforePrefix=q;b.prefix=r;b.suffix=o;n.push(b);if((d=window.ue)&&d.count){var f=i+b.alias.replace("-","");d.count(f,d.count(f)+1)}}if(n.length===
g)return!1})}k.suggestionSets[i]=n;var s=a.createEvent(i,m.suggestionsReady);c.eventBus.trigger(s,k)}}(function(){var b=a.createEvent(i,m.suggestionsNeeded);c.eventBus.listen(b,p)})()}var i="department",h=3,g=3;f.prototype.getName=function(){return i};return f});window.$Nav.when("sx.iss.utils").build("sx.iss.HelpSuggestionProvider",function(d){var c=[{type:"help",pat:/^return/i,text:"Looking for help with returns? Try this.",url:""},{type:"help",pat:/^track/i,text:"Looking for help with tracking? Try this.",
url:""},{type:"help",pat:/^gift[\s*]w/i,text:"Looking for help with gift wrapping? Try this.",url:""},{type:"help",pat:/^canc/i,text:"Looking for help with order cancellation? Try this.",url:""},{type:"help",pat:/^refu[\s*]/i,text:"Looking for help with refund? Try this.",url:""},{type:"help",pat:/^passw[\s*]/i,text:"Looking for help with passwords? Try this.",url:""},{type:"help",pat:/^log(ging\s*)?o/i,text:"Looking for help with logging out? Try this.",url:""}];return function(){this.getName=function(){return"help"};
d.eventBus.listen("help-suggestionsNeeded",function(b){var e,a=[];for(e=0;e<c.length;e++)b.match(c[e].pat)&&a.push(c[e]);d.eventBus.trigger("help-suggestionsReady",{searchTerm:b,suggestions:a})},this)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.RecentSearchSuggestionProvider",function(d,c){return function(){var b=/[^\w]/;this.getName=function(){return"recent"};c.eventBus.listen("recent-suggestionsNeeded",function(e){var a=[];if(window.sx&&window.sx.searchsuggest&&window.sx.searchsuggest.searchedText){var f=
window.sx.searchsuggest.searchedText,i={},h,g,j,m,p,l,k=!e||!b.test(e)?e:d("<div></div>").text(e).html();for(m=0;m<f.length;m++)if(g=f[m].keywords,h=!g||!b.test(g)?g:d("<div></div>").html(g).text(),j=c.suggestionUtils.getPrefixPosMultiWord(g,k),!i[g]&&c.suggestionUtils.getPrefixPosMultiWord(h,e)!==-1)j===-1?(j=g,l=p=""):(p=c.suggestionUtils.splitStringForDisplay(g,j,k.length),j=p.bprefix,l=p.prefix,p=p.suffix),a.push({type:"recent",spellCor:!1,bprefix:j,prefix:l,suffix:p,keyword:h,originalKeywords:g,
deleteUrl:f[m].deleteUrl}),i[g]=1}c.eventBus.trigger("recent-suggestionsReady",{searchTerm:e,suggestions:a})},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(d,c,b){return function(c,a,f){var i,h;this.getDisplay=function(a){if(i(a))return d.extend(a,f),h(a)};i=typeof c==="string"?function(a){return a.type===c}:c;h=b(a)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.SuggestionHighlightingProvider",function(d,c){return function(){function b(a){a=
a.currentTarget.id;h&&h.removeClass(h.attr("data-selected-class"));h=d("#"+a);i=parseInt(a.substr(6));h.addClass(h.attr("data-selected-class"))}function e(a){a=a.currentTarget.id;h&&h.attr("id")===a&&(h.removeClass(h.attr("data-selected-class")),h=void 0,i=-1)}var a=this,f,i=-1,h;c.eventBus.listen("suggestionsDisplayed",function(c){var j;f=c;i=-1;h=void 0;for(c=0;c<f.suggestions.length;c++)j=d("#"+f.suggestions[c].suggestionId),j.bind("mouseover",a,b).bind("mouseout",a,e)},this).listen("upArrowPressed",
function(){f&&(h&&h.removeClass(h.attr("data-selected-class")),i--,i===-1?c.eventBus.trigger("suggestionSelected",{keyword:f.searchTerm}):(i===-2&&(i=f.suggestions.length-1),h=d("#issDiv"+i),h.addClass(h.attr("data-selected-class")),c.eventBus.trigger("suggestionSelected",f.suggestions[i])))},this).listen("downArrowPressed",function(){f&&(h&&h.removeClass(h.attr("data-selected-class")),i++,i===f.suggestions.length?(i=-1,c.eventBus.trigger("suggestionSelected",{keyword:f.searchTerm})):(h=d("#issDiv"+
i),h.addClass(h.attr("data-selected-class")),c.eventBus.trigger("suggestionSelected",f.suggestions[i])))},this)}});window.$Nav.when("sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(d,c,b){return function(e,a,f,i,h){function g(a){d.eventBus.trigger(i.suggestionsNeeded,a)}function j(b){var e=a.sequence(b),b=b.searchTerm,g=l++;d.timingProvider.startTimer("IssDisplayProvider",g);if(e.length===0)d.eventBus.trigger(i.noSuggestions,b);else{for(var j=
f,q=0,r=0;r<e.length;r++){var o=e[r];if(o.type!=="separator")o.suggestionId="issDiv"+q,q++;var s=o,x="";x+=o.isDeepNode===!0?"s-highlight-secondary":"s-highlight-primary";s.cssClasses=x;for(var w,s=0;s<j.length;s++)if(w=j[s],w=m(w,o),w=w.getDisplay(o))break;o.display=w}j=e&&e.length>0&&e[0].type===c.a9Corpus.name&&h.hasOwnProperty("issCorpusSugText");j=p({suggestions:e,suggestionTitle:j?h.issCorpusSugText:h.hasOwnProperty("sugText")?h.sugText:""});d.timingProvider.stopTimer("IssDisplayProvider",g);
d.eventBus.trigger(i.suggestionsReadyForDisplay,{searchTerm:b,display:j,suggestions:e})}}function m(a,b){var c=a;if(a.hasOwnProperty("provider")&&a.hasOwnProperty("partials")){for(c=0;c<a.partials.length;c++){var d=a.partials[c],f=d.provider.getDisplay(b);d.hasOwnProperty("formatter")&&(f=d.formatter.string.replace(d.formatter.toReplace,f));b[d.key]=f}c=a.provider}return c}var p=b(e),l=0;(function(){d.eventBus.listen(i.suggestionsReady,j,this);d.eventBus.listen(["parentFocused","searchTermChanged"],
g,this)})();return{processPartials:m}}});window.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.ArraySuggestionProvider",function(d,c){return function(b,e){function a(a){for(var b=[],a=a.toLowerCase(),l=0;l<i.length;l++){var k=i[l];if(k.toLowerCase().indexOf(a)!==-1&&b.length<g){var k={term:k,searchTerm:a,url:h[l]},n=d.suggestionUtils.getPrefixPos(k.term,k.searchTerm),n=d.suggestionUtils.splitStringForDisplay(k.term,n,k.searchTerm.length),k={type:j,bprefix:n.bprefix,prefix:n.prefix,suffix:n.suffix,
keyword:k.searchTerm,url:k.url,isExactMatch:k.term===k.searchTerm};b.push(k)}}a={searchTerm:a,suggestionSets:{array:b}};b=c.createEvent(f,e.suggestionsReady);d.eventBus.trigger(b,a)}var f="array",i=b[0],h=b[1],g=10,j="array";(function(){var b=c.createEvent(f,e.suggestionsNeeded);d.eventBus.listen(b,a,this)})();return{name:f}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.TemplateEngine","NavDomApi","sx.iss.SuggestionTypes","sx.iss.ReftagBuilder").build("sx.iss.DesktopSearchBoxEventHandler",
function(d,c,b,e,a,f,i){var h=a.getSearchApi();return function(g){function j(){t=!0;q||(q=!0)}function m(){u=!0}function p(){a.activateSearchBox()}function l(){a.deactivateSearchBox()}c.eventBus.listen(g.selectionChange,function(f){k===void 0&&(k=a.getAliasFromDropdown());if(f.isScrollIntoSearchBox===!0)f=f.previousSearchTerm,a.getIssPrefixElem().remove(),n.val(f),a.getAliasDropdown().val("search-alias="+k).trigger("change");else{var g=c.timingProvider.getTimingWithDisplayLatency(b.latency.group,
b.latency.events.timeToDisplay),g=a.getKeyword()+","+a.getOriginalAlias()+","+g,h=a.getIssPrefixElem();h.length>0?h.attr("value",g):(g=d('<input type="hidden"/>').attr("id","issprefix").attr("name","sprefix").attr("value",g),a.getForm().append(g));var f=f.suggestion,i=f.attr("data-alias"),h=a.getOption(i),g=a.getAliasDropdown(),i="search-alias="+i;h.length===0?(h=f.data("store"),h!==void 0&&h!==""&&g.append(e("s-option",{value:i,store:h}))):i=h.val();g.val(i).trigger("change");a.setKeyword(f.attr("data-keyword"))}});
c.eventBus.listen(g.hideDropdown,function(b){t===!0&&u===!0&&(b.keyCode===27||b.keyCode===13)?(t=u=!1,c.eventBus.triggerThrottledEvent(g.suggestionsNeeded,a.getKeyword())):(a.hideDropdown(),a.getIssPrefixElem().remove(),k=void 0)});c.eventBus.listen(g.suggestionClicked,function(b){var d=b.suggestion;c.eventBus.trigger(g.updateSearchBox,d);b={suggestion:d,searchTerm:a.getKeyword(),previousSearchTerm:b.previousSearchTerm};c.eventBus.trigger(g.selectionChange,b);a.hideDropdown();d.attr("data-type")===
f.a9Corpus.name?(d=d.attr("data-url"),window.location=d.replace(f.a9Corpus.reftagTemplate,(new i).buildFull(b,q))):a.submitForm()});c.eventBus.listen(g.noSuggestions,function(){a.hideDropdown()});c.eventBus.listen(g.suggestionsNeeded,function(){k=a.getAliasFromDropdown()});h===void 0&&(c.eventBus.listen(g.searchBoxFocusIn,p),c.eventBus.listen(g.searchBoxFocusOut,l));h!==void 0?(h.on("compositionstart",j),h.on("compositionend",m)):d("#navbar").delegate("#twotabsearchtextbox","compositionstart",j).delegate("#twotabsearchtextbox",
"compositionend",m);var k,n=a.getSearchBox(),t=!1,u=!1,q=!1;return{getWasCompositionUsed:function(){return q}}}});window.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(d){return function(){var c;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder",events:"click"}};this.handleEvent=function(b){var e=b.target||b.srcElement,b=parseInt(b.currentTarget.id.substr(6),10);e.className&&e.className.indexOf("suggest_builder")!=-1?
d.eventBus.trigger("updateSearchTerm",c.suggestions[b].keyword):d.eventBus.trigger("suggestionClicked",{suggestion:c.suggestions[b]})};d.eventBus.listen("suggestionsDisplayed",function(b){c=b},this)}});window.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(d){return function(){function c(a){var b,c,e,g;b=location.protocol+"//"+location.host+a.deleteUrl;c=window.sx.searchsuggest.searchedText;for(e=0;e<c.length;e++)if(c[e].keywords===a.originalKeywords){g=e;break}g!==
-1&&c.splice(g,1);d.eventBus.trigger("focusOnParent");var j;window.XMLHttpRequest?j=new XMLHttpRequest:window.ActiveXObject&&(j=new ActiveXObject("Microsoft.XMLHTTP"));if(j&&b)try{j.open("GET",b,!0),j.send(null)}catch(m){}}var b=this,e;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(a){var f=a.target||a.srcElement,a=parseInt(a.currentTarget.id.substr(6),10);f.className&&f.className.indexOf("iss_sh_delete")!=-1?c.call(b,e.suggestions[a]):
d.eventBus.trigger("suggestionClicked",{suggestion:e.suggestions[a]})};d.eventBus.listen("suggestionsDisplayed",function(a){e=a},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.DomUtils","sx.iss.TimingEvents","sx.iss.TemplateEngine","sx.iss.DebugUtils").build("sx.iss.SearchBoxEventHandler",function(d,c,b,e,a,f){var i=[37,38,39,40,91,92,93,192];return function(a,e,j){function m(a){c.eventBus.trigger(j.keydown);var e=a.keyCode,g=e===40,h=e===38,i;if(q.find("#suggestions-template").is(":visible")){if(g||
h){o===void 0&&(o=b.getKeyword(r));var k=q.find(".s-suggestion"),n=k.index(d(".s-selected"));(h=n===0&&h||n+1===k.length&&g)?q.find(".s-suggestion").removeClass("s-selected"):(f.logDebug("highlighting suggestion"),i=q.find(".s-suggestion"),k=i.index(t()),n=i.length,g?(g=-1,k===-1||k===n-1?g=0:k<n&&(g=k+1)):(g=-1,k<1?g=n-1:k<=n&&(g=k-1)),i.eq(k).removeClass("s-selected"),g=i.eq(g),g.addClass("s-selected"),i=g);c.eventBus.trigger(j.selectionChange,{suggestion:i,isScrollIntoSearchBox:h,searchTerm:o,
previousSearchTerm:s});r.val()!==""&&a.preventDefault()}e===13&&(e=t(),e.length>0&&(c.eventBus.trigger(j.suggestionClicked,{suggestion:e,searchTerm:o,previousSearchTerm:s}),a.preventDefault()))}}function p(a){a=a.keyCode;a===13?n(a):a===27?n(a):(o=b.getKeyword(r),o!==s&&i.indexOf(a)===-1&&(o===void 0||o===""?(n(),s=""):(c.eventBus.triggerThrottledEvent(j.suggestionsNeeded,o),s=o)))}function l(){setTimeout(function(){return function(){n();c.eventBus.trigger(j.searchBoxFocusOut)}}(),300)}function k(){c.eventBus.trigger(j.searchBoxFocusIn)}
function n(a){o=void 0;c.eventBus.trigger(j.hideDropdown,{keyCode:a})}function t(){return q.find(".s-suggestion.s-selected")}var u,q,r,o,s;(function(){if(e!==void 0){u=e.$form;q=e.$dropdown;r=e.$searchbox;var a="#"+r.attr("id");u.delegate(a,"focusin",k).delegate(a,"focusout",l).delegate(a,"keydown",m).delegate(a,"keyup",p);s=r.val()}})()}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.DebugUtils").build("sx.iss.SuggestionEventHandler",function(d,c,b,e,a){return function(b,
i){i.delegate(".s-suggestion","click",function(e){var g=d(this);a.logDebug("Suggestion clicked",g);c.eventBus.trigger(b.suggestionClicked,{suggestion:g});e.preventDefault()}).delegate(".s-suggestion","mouseover",function(a){e.hoverOverEl(d(a.currentTarget))}).delegate(".s-suggestion","mouseout",function(a){e.hoverOutEl(d(a.currentTarget))})}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.CustomSearchBoxEventHandler",function(d,c,b,e){return function(a,f,
i){function h(a){m.hide();typeof i.manualOverride==="function"&&(a=i.manualOverride(a),a!==null&&a.length>0&&g(a));d(i.submitId).removeAttr("disabled")}function g(a){j.find(e.hiddenInputClass).remove();a=e.getFormParams(a);b.logDebug("Updating form with params.",a);j.attr("action",a.uri);for(var c="",a=a.formParams,d=0;d<a.length;d++){var f=a[d],g=decodeURIComponent(f.value);c+='<input type="hidden" class="'+e.hiddenInputValue+'" name="'+f.name+'" value="'+g+'"/>'}j.append(c)}var j,m;j=a.$form;m=
a.$dropdown;c.eventBus.listen(f.suggestionClicked,function(a){b.logDebug("Suggestion clicked",a);g(a.suggestion.data("url"));j.submit()});c.eventBus.listen(f.noSuggestions,function(a){h(a)});c.eventBus.listen(f.suggestionsReadyForDisplay,function(a){a.suggestions.length===2&&a.suggestions[1].type==="separator"&&a.suggestions[0].isExactMatch===!0?(a=m.find(e.suggestionClass).eq(0),g(a.data("url"))):a.searchTerm.length>=4?h(a.searchTerm):d(i.submitId).attr("disabled","disabled")});c.eventBus.listen(f.hideDropdown,
function(){m.hide()})}});window.$Nav.when("sx.iss.utils","sx.iss.Events","sx.iss.TimingEvents","sx.iss.MetricsLogger").build("sx.iss.SuggestionAggregator",function(d,c,b,e){return function(a,f){function i(h){d.timingProvider.startTimer(b.latency.group,b.latency.events.timeToDisplay);e.startEndToEndLogging();if(!g[h]){g[h]={remainingProviders:f.length,searchTerm:h,suggestionSets:{}};for(var i=0;i<f.length;i++){var p=c.createEvent(f[i],a.suggestionsNeeded);d.eventBus.trigger(p,h)}}}function h(b){var c=
g[b.searchTerm],b=b.suggestionSets,f;for(f in b)b.hasOwnProperty(f)&&(c.suggestionSets[f]=b[f]);--c.remainingProviders||(delete g[c.searchTerm],d.eventBus.trigger(a.suggestionsReady,c))}var g={};(function(){for(var b=0;b<f.length;b++){var e=c.createEvent(f[b],a.suggestionsReady);d.eventBus.listen(e,h,this)}d.eventBus.listen(a.suggestionsNeeded,i,this)})()}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes").build("sx.iss.SuggestionSequencer",function(d,c,b){return function(d){var a=[b.department.name,
b.a9Corpus.name,b.a9XOnly.name,b.a9Xcat.name,b.a9.name,"array"],f={type:"separator"};this.sequence=function(b){for(var c=b.suggestionSets,b=[],g=0,j=this.isDeepNode(d),m=0;m<a.length;m++){var p=c[a[m]];if(!(typeof p==="undefined"||p.length===0)){for(var l=0;l<p.length&&g<10;l++){var k=p[l];k.dispIdx=b.length;b.push(k);g++}g>0&&!j&&b.push(f)}}j&&(b=this.sequenceDeepNodeResults(b));c=b.length;c>0&&b[c-1].type==="separator"&&b.splice(-1,1);return b};this.isDeepNode=function(a){var b,d;a.deepNodeISS&&
(b=c.suggestionUtils.getDeepNodeAlias(a.deepNodeISS),d=c.suggestionUtils.getDeepNodeCategoryName(b,a.deepNodeISS));return b!==void 0&&d!==void 0};this.sequenceDeepNodeResults=function(a){for(var c,d,f=[],e=0;e<a.length;e++)d=a[e],(c===b.a9Xcat.name||c===b.a9XOnly.name)&&d.type===b.a9.name?f.unshift(d):f.push(d),c=d.type;return f}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi").build("sx.iss.MetricsLogger",function(d,c,b,e){function a(){var a=e.isSearchBoxFocused()?j:g;ue.tag(a)}
function f(){uet(m,h,k);uet(p,h,k);uex(l,h,k)}function i(){return typeof uet==="function"&&typeof uex==="function"}var h="iss-init-pc",g="iss-on-time",j="iss-late",m="cf",p="be",l="ld",k={wb:1};i()&&(c.eventBus.listen(b.globals.initializeNavSearchBox,a),c.eventBus.listen(b.globals.issLoaded,f));return{startEndToEndLogging:function(){i()&&uet("bb","iss-end-to-end-a9",k)},stopEndToEndLogging:function(){i()&&(uet(m,"iss-end-to-end-a9",k),uet(p,"iss-end-to-end-a9",k),uex(l,"iss-end-to-end-a9",k))}}});
window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.SuggestionTypes","sx.iss.SearchBoxEventHandler","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.DesktopSearchBoxEventHandler","NavDomApi","sx.iss.Events","sx.iss.Reftag","sx.iss.Weblab","sx.iss.DebugUtils","sx.iss.MetricsLogger").build("sx.iss.IssParentCoordinator",
function(d,c,b,e,a,f,i,h,g,j,m,p,l,k,n,t,u,q,r,o){return function(s){function x(a){var b={provider:new g(a.name,a.templateId)};return a===e.a9Xcat||a===e.a9XOnly?d.extend(b,{partials:[{key:"storeHtml",provider:new g(a.name,"s-storeText"),formatter:{string:s.deptText,toReplace:"{department}"}}]}):b.provider}var w,y,v=!1;r.isQIAEnabled()&&d.extend(s,{cf:1});y={$form:n.getForm(),$dropdown:n.getDropdown(),$searchbox:n.getSearchBox()};w=t.createInstance();n.getForm().data("originalSearchTerm",n.getKeyword());
n.getForm().data("originalAlias",n.getAliasFromDropdown());(function(){new a(s,y,w);p.init();var b=[(new f("desktop",s,w)).getName()],d=[x(e.a9),x(e.a9Corpus),new g("separator","s-separator"),x(e.a9Xcat),x(e.a9XOnly)];if(s.hasOwnProperty("isDigitalFeaturesEnabled")&&s.isDigitalFeaturesEnabled===1){d.push(new g(e.department.name,e.department.templateId));var o=new i(s,w);b.push(o.getName())}new m("suggestions-template",new j(s),d,w,s);new h(w,b);c.eventBus.trigger(t.globals.initializeNavSearchBox);
b=new k(w,s);new u(w,s,{shouldAddImeTag:b.getWasCompositionUsed});new l(w,n.getDropdown());new q(s,w)})();c.eventBus.listen(w.suggestionsReadyForDisplay,function(a){v&&(y.$searchbox.val().length===0?r.logDebug('Search term is empty, abort rendering for the search term "'+a.searchTerm+'"'):(n.showDropdown(a.display),c.timingProvider.stopTimer(b.latency.group,b.latency.events.timeToDisplay),o.stopEndToEndLogging(),c.eventBus.trigger(w.suggestionsRendered,a),c.eventBus.trigger(t.globals.suggestionsRendered,
a)))});c.eventBus.listen(w.hideDropdown,function(){v=!1});c.eventBus.listen(w.suggestionsNeeded,function(){v=!0})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SearchBoxEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.Events","sx.iss.DomUtils","sx.iss.ArraySuggestionProvider","sx.iss.CustomSearchBoxEventHandler").build("sx.iss.CustomParentCoordinator",
function(d,c,b,e,a,f,i,h,g,j,m,p,l){return function(k){var n,t;(function(){h.init();n=j.createInstance();var c=k.searchboxId,q=d(k.formId),r=d('<div id="search-dropdown-custom" class="search-dropdown"></div>');q.after(r);t={$form:q,$dropdown:r,$searchbox:d(c)};t.$dropdown.css({width:t.$searchbox.outerWidth()});new b(k,t,n);new g(n,t.$dropdown);new l(t,n,k);k.hasOwnProperty("src")&&m.isArray(k.src)&&(c=new p(k.src,n),new e(n,[c.name]));c=[new a("array","s-minimal")];new i("suggestions-template",new f(k),
c,n,k)})();c.eventBus.listen(n.suggestionsReadyForDisplay,function(a){t.$dropdown.html(a.display);t.$dropdown.show();c.eventBus.trigger(n.suggestionsRendered,a)});return{dropdownId:"search-dropdown-custom"}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.A9SearchSuggestionEventHandler","sx.iss.HelpSuggestionProvider","sx.iss.RecentSearchSuggestionProvider","sx.iss.RecentSearchSuggestionEventHandler","sx.iss.SuggestionHighlightingProvider",
"sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencer","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinator","sx.iss.PublicApi","sx.iss.MetricsLogger","sx.iss.CustomParentCoordinator").build("sx.iss",function(d,c,b,e,a,f,i,h,g,j,m,p,l,k,n,t,u,q){e={A9SuggestionProvider:e,DepartmentSuggestionProvider:a,A9SearchSuggestionEventHandler:f,HelpSuggestionProvider:i,RecentSearchSuggestionProvider:h,RecentSearchSuggestionEventHandler:g,SuggestionHighlightingProvider:j,
SuggestionAggregator:m,SuggestionSequencer:p,SuggestionDisplayProvider:l,IssDisplayProvider:k,IssParentCoordinator:n,CustomParentCoordinator:q,IssParentCoordinatorMobile:n,SuggestionSequencerMobile:p,isNewIss:!0};d.extend(e,e,t);c.eventBus.trigger(b.globals.issLoaded);return e});window.$Nav.when("sx.iss").run(function(d){window.$Nav.publish("sx.iss",d);window.$Nav.publish("search-js-autocomplete",d)})})})(function(){var D=window.AmazonUIPageJS||P,d=D.attributeErrors;return d?d("RetailSearchAutocompleteAssets"):
D}());
;/* RetailSearchClientSideLoggingAuiAssets */
(function(d){d.execute(function(){if(!window.$SearchJS&&window.$Nav)window.$SearchJS=$Nav.make("sx");window.$SearchJS&&($SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"}),$SearchJS.importEvent("jQuery",{global:"jQuery"}),$SearchJS.when("jQuery").run("searchCSL-lib",function(c){c.searchCSL=c.searchCSL||new function(){var b=this,g=[],e=[],d,i,j,f,h=200,k;b.init=function(a,l,c){a&&l&&!d&&(d=a,b.updateRid(l),c&&(h=c))};b.updateRid=function(a){a&&i!=a&&(b.tx(),i=a,j={})};b.addWlt=function(a){if(a){if(a.call&&
(a=a(),!a))return;j[a]||(g.push(a),j[a]=1,b.scheduleTx())}};b.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(e.push(a),b.scheduleTx())};b.scheduleTx=function(){if(h==0)b.tx();else{if(!k){var a=window.onbeforeunload;window.onbeforeunload=function(c){f&&(window.clearInterval(f),f=void 0);b.tx();k=!1;return a&&a.call?a(c):void 0};k=!0}!f&&h>0&&(f=window.setTimeout(function(){f=void 0;b.tx()},h))}};b.tx=function(){if(g.length||e.length){var a="/mn/search/csl?";g.length&&
(a+="rrid="+i+"&cpt="+d+"&ctw="+g.join("|"),g=[]);if(e.length){var b="";c.each(e,function(a,d){b+=d.rid+":";c.each(d.selections,function(a,c){c&&(b+=c+(a!=d.selections.length-1?",":""))});b+=a!=e.length-1?".":""});e=[];b&&(a+=a.charAt(a.length-1)=="?"?"":"&",a+="amabotSelections="+b)}(new Image).src=a}}};$SearchJS.publish("search-csl",c.searchCSL)}))})})(function(){var d=window.AmazonUIPageJS||P,c=d.attributeErrors;return c?c("RetailSearchClientSideLoggingAuiAssets"):d}());
;/* P13NSharedSitewideJS */
(function(c){c.execute(function(){(function(){c.register("p13n-sc-math",function(){return Math});c.register("p13n-sc-document",function(){return document});c.register("p13n-sc-window",function(){return window});c.register("p13n-sc-undefined",function(){});var b=function(){return window.P&&window.P.AUI_BUILD_DATE};b()?(c.when("jQuery").register("p13n-sc-jQuery",function(b){return b}),c.when("ready").register("p13n-sc-ready",function(){})):window.amznJQ&&(window.amznJQ.available("jQuery",function(){c.register("p13n-sc-jQuery",
function(){return window.amznJQ.jQuery})}),window.amznJQ.onReady("jQuery",function(){c.register("p13n-sc-ready",function(){})}),window.amznJQ.available("amazonShoveler",function(){c.register("p13n-sc-amznJQ-shoveler",function(){})}));c.when("p13n-sc-window").register("p13n-sc-util",function(f){var g=f.ueLogError;typeof g!=="function"&&(g=function(b,f){if(f&&f.message)throw Error(f.message);if(b&&b.message)throw Error(b.message);});var c=function(b,f){g({logLevel:b,attribution:"P13NSharedSitewideJS",
message:"[p13n-sc] "+f})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:f.ue&&f.ue.count||function(){},isAUI:b,log:{warn:function(b){c("WARN",b)},error:function(b){c("ERROR",b)}}}})})();c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,f,c){var i=f.clearInterval,e={},k,l,a=function(){if(!k){var a=f.setInterval(function(){var b=a,f=(new Date).getTime();b!==k?i(b):((!l||f-l>200)&&j(),l=(new Date).getTime())},200);k=a}},j=function(){b.each(e,
function(a,b){b.call(f)})};return{subscribe:function(b,d){e[b]||(e[b]=d,a())},unsubscribe:function(a){e[a]&&delete e[a];var a=!0,b;for(b in e)e.hasOwnProperty(b)&&(a=!1);a&&(i(k),k=c)}}});c.when("p13n-sc-jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,f){var c=[],i=b(window),e=function(){for(var b=i.scrollTop()+i.height(),e=i.scrollLeft()+i.width(),a=c.length-1;a>=0;a--){var j=c[a],h=j.callback,d=j.$element,o=j.distanceY,j=j.distanceX;if(d.parents("body").size()===0)c.splice(a,
1);else if(!d.is(":hidden")){var n=d.offset();b-o>n.top&&e-j>n.left&&(h.call(null,d[0]),c.splice(a,1))}}c.length===0&&f.unsubscribe("p13n-sc-call-on-visible")};return{register:function(k,i,a){var j=a&&typeof a.distance!=="undefined"?a.distance:0,h=a&&typeof a.distanceY!=="undefined"?a.distanceY:j,d=a&&typeof a.distanceX!=="undefined"?a.distanceX:0;b(k).each(function(){c.push({$element:b(this),callback:i,distanceY:h,distanceX:d})});f.subscribe("p13n-sc-call-on-visible",e);e()}}});c.when("A","jQuery",
"p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math").register("p13n-sc-view-trigger",function(b,f,g,i,e){var k=function(a){var c=f(a),a=c.attr("data-params"),h=c.attr("data-url");if(a&&h){var a=b.parseJSON(a),d=c.offset(),c=[d.top,d.left,c.height(),f(window).width()];a.elementRect=c.join(",");var g=0,k={cache:!0,crossDomain:!1,data:f.param(a,!1),error:function(a){a=a.status||0;g>=3||a>=400&&a<500||setTimeout(i,200*e.pow(2,g))},global:!1,url:h},i=function(){g+=1;f.ajax(k)};i()}},l=function(a){var e=
f(a);if(e.size()===1){var h=e.attr("data-params"),h=h?b.parseJSON(h):{};if(!(h.allowEmpty!==!0&&e.text().trim().length===0)){var d=e.height();if(!(h.allowEmpty!==!0&&d<5)){d=0;if(typeof h.distance==="number")d=h.distance;e.attr("data-p13n-sc-vt-initialized")||(e.attr("data-p13n-sc-vt-initialized",!0),g.register(a,function(){k(a)},{distance:d}))}}}},i=function(){b.each(f(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(a){l(a)})};c.execute(i);c.when("afterReady").execute("p13n-sc-view-trigger:init",
i);return{initializeElement:l}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-window","p13n-sc-document","p13n-sc-ready").register("p13n-sc-logger",function(b,f,c,i){function e(a){return a.join("")}function k(a,b){var d=a.attr(b),h={};d!==void 0&&d!==null&&(h=typeof c.JSON!=="undefined"?JSON.parse(d):eval("("+d+")"));return h}function l(a,d){for(var h=[a.widget,":"],f=0;f<a.asins.length;f++){var c=a.asins[f];h.push(c.asin,"@");b.each(c,function(a,b){a!=="asin"&&h.push(a,"=",b,"|")});h.splice(h.length-
1,1);h.push(",")}a.asins.length>0&&h.splice(h.length-1,1);d&&(h.push(":","action=",a.action),b.each(a.meta,function(a,b){h.push(",",a,"=",b)}));return e(h)}function a(a,d){var h=k(b(d),"data-p13n-asin-metadata");if(h&&h.asin){var f=h.asin,e=k(b(a),"data-p13n-asin-metadata");e&&b.extend(!0,h,e[f]);return h}}function j(a,h){var j=new Image;f.count("p13n:logger:attempt",1);j.onerror=function(){d++;f.count("p13n:logger:error",1)};j.src=e(["https:"===i.location.protocol?"https://":"http://",c.ue_furl||
"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",h,e(["?",b.param(k(b(a.featureElement),"data-p13n-global"))])])}function h(){return d>3?(o||(f.log.warn("impression image load failed too many times, no longer logging impressions"),f.count("p13n:logger:abort",1),o=!0),!0):!1}var d=0,o=!1,n={},p={},q={logAction:function(d){if(!h())if("featureElement"in d)if("action"in d){var c=b(d.featureElement);d.asins=b.map(b(d.featureElement).find(".p13n-asin").filter(":visible"),function(b){return a(c,
b)});d.meta=d.meta||{};var g=k(c,"data-p13n-feature-metadata");b.extend(!0,d.meta,g);d.widget=c.attr("data-p13n-feature-name");d.widget in n||(n[d.widget]={});for(var i=g=0;i<d.asins.length;i++)d.asins[i].asin in n[d.widget]||(n[d.widget][d.asins[i].asin]=!0,g++);d.logOnlyOnNew&&g===0||(g=e(["action/",e([d.widget,"_:",d.action,"@v=",d.eventtime||0,",impressed@v=",g]),"/",l(d,!0)]),d.replicateAsinImpressions&&(i=e(["asin/",l(d,!1)]),g=e(["batch/",g,"$",i])),j(d,g))}else f.log.warn("action missing in eventData for logAction");
else f.log.warn("featureElement missing in eventData for logAction")},logAsyncAction:function(a){var d=(new Date).getTime(),h=typeof a.initialDelay==="number"?a.initialDelay:400,f=typeof a.timeout==="number"?a.timeout:5E3,e=b(a.featureElement);a.widget=e.attr("data-p13n-feature-name");a.widget in p&&c.clearTimeout(p[a.widget]);var j=function(){var b=a.isEventComplete(),h=(new Date).getTime();if(h-d<f&&!b)p[a.widget]=c.setTimeout(j,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=
h-d;delete p[a.widget];q.logAction(a)}};p[a.widget]=c.setTimeout(j,h)},eventPending:function(a){return b(a).attr("data-p13n-feature-name")in p},impressAsin:function(d){if(!h())if("featureElement"in d)if("faceoutElement"in d){var c=b(d.faceoutElement),g=b(d.featureElement);d.widget=g.attr("data-p13n-feature-name");d.asins=[a(g,c)];c=e(["asin/",l(d,!1)]);j(d,c)}else f.log.warn("faceoutElement missing in eventData for logAction");else f.log.warn("featureElement missing in eventData for logAction")}};
return q});c.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger","ready").register("p13n-sc-faceout-logger",function(b,f,c,i){var e=function(f,e){var a=b(f),j=b(e);a.length===1&&!a.attr("data-p13n-sc-fl-initialized")&&(a.attr("data-p13n-sc-fl-initialized",!0),c.register(a,function(){i.impressAsin({featureElement:j,faceoutElement:a})}))};f.on("p13n:faceoutsloaded",function(f){b(f).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,a){e(a,f)})})});c.when("A","jQuery").register("p13n-sc-lazy-image-loader",
function(b,f){return{loadImages:function(c){b.executeDeferred();c.find(".p13n-sc-lazy-loaded-img").each(function(c,e){var g=f(e),l=g.find(".a-dynamic-image");l.load(function(){g.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(l)})}}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-math","p13n-sc-line-truncator-settings").register("p13n-sc-line-truncator",function(b,f,c,i){function e(a){this.$element=a;this.$experimentElement=b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=
a.data("rows");this.lineHeight=i.lineHeight;this.maxRows||f.log.error("Truncation element missing necessary line number data")}var k=/(?=[ \-\/])/,l=/[^\/\-\[\]():\s]/;e.prototype.truncate=function(){var a=this.$element.html();this.$element.append(this.$experimentElement);if(!this.checkLineFit(a)){var b=this.truncateByToken(a);b?(this.$element.html(b),this.$element.attr({title:a})):f.log.error("Unable to successfully truncate line "+a)}this.$experimentElement.remove()};e.prototype.checkLineFit=function(a){this.$experimentElement.html(a);
a=this.$experimentElement.get(0).clientHeight/this.lineHeight;return c.round(a)<=this.maxRows};e.prototype.truncateByToken=function(a){for(var a=a.split(this.getTokenSeparatorRegex()),b=1,h=a.length,d,f,e=0;b!==h;)if(d=c.floor((h+b)/2),f=a.slice(0,d).join("")+"&hellip;",this.checkLineFit(f)){if(h-d<=1){for(e=d;e>0&&!l.test(a[e-1]);)e--;break}b=d}else h=d;return e===0?void 0:a.slice(0,e).join("")+"&hellip;"};e.prototype.getTokenSeparatorRegex=function(){return this.$element.data("truncateByCharacter")?
"":k};return{truncateLines:function(a){a.find(".p13n-sc-truncate").each(function(){var a=new e(b(this));a&&a.truncate()})}}});c.register("p13n-sc-line-truncator-settings",function(){return{lineHeight:19}});c.when("A","jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,f,c,i,e,k){function l(a,b){var c=a.getAttr("pageNumber"),g=a.dom.$container;g.data("p13nPreviousPage",c);e.logAsyncAction(f.extend(!0,{},{featureElement:g,
isEventComplete:function(){return g.find(".a-carousel-card-empty").size()===0&&!a.getAttr("animating")},meta:{page:c},replicateAsinImpressions:!0},b))}function a(a){j(a)&&i.register(a.dom.$container,function(){l(a,{action:"view"})})}var j=function(a){return typeof a==="undefined"?!1:a.dom.$container.data(k.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(c.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&a(b)});b.on("a:carousel:init",function(b){a(b.carousel)});
f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"next_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"prev_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(a){a=c.getCarousel(a.target);l(a,{action:"start_over",meta:{op:a.dom.$container.data("p13nPreviousPage")}})});
b.on("a:carousel:change:pageSize",function(a){a=a.carousel;j(a)&&a.dom.$container.hasClass("a-carousel-initialized")&&l(a,{action:"resize",logOnlyOnNew:!0})})});c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-document","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","p13n-sc-amznJQ-shoveler").register("p13n-sc-non-aui-carousel",function(b,f,g,i,e,k){var l=function(a){k.count("p13n-sc-non-aui-carousel:init",1);var d=a.attr("data-widgetname"),c=b("#"+d+"Data");if(c.length!==1)return!1;if(a.attr("data-p13n-sc-carousel-initialized"))return!1;
else a.attr("data-p13n-sc-carousel-initialized",!0);var g=c.text().split(","),j=a.find(".shoveler-content > ul"),i="input#"+d+"ShvlState",m=function(){},l=200,u=!1,w=function(){var d=l;a.find(".p13nimp, .p13n-asin").each(function(){var a=b(this).outerHeight(!0);a>d&&(d=a)});d>l&&(l=d,j.animate({height:d},200,"linear"));u||x()},x=function(){var b=l/2;a.find("a.next-button, a.back-button").css("top",b);u=!0},r=a.find(".shoveler").shoveler(function(a,d){var e="",e=typeof f.JSON!=="undefined"?JSON.parse(c.attr("data-ajax")):
eval("("+c.attr("data-ajax")+")");e.asins=g.slice(a,a+d).join(",");e.count=d;e.offset=a;e=b.param(e);return c.attr("data-url")+"?"+e},g.length,{cellTransformer:function(a){return a===null?"":a},cellChangeSpeedInMs:30,preloadNextPage:!0,prevButtonSelector:"a.back-button",nextButtonSelector:"a.next-button",startOverSelector:"span.start-over",startOverLinkSelector:"a",horizPadding:14,state:{ready:function(){return b(i).val().length>0},get:function(){return parseInt(b(i).val(),10)},set:function(a){b(i).val(a)}},
onUpdateUIHandler:function(){w();m()}}),v=0,y=function(){var a=b(f).width();v!==a&&(r.updateUI(),v=a)},t=null;a.resize(function(){t&&f.clearTimeout(t);t=f.setTimeout(y,100)});var s=function(d){e.logAsyncAction(b.extend(!0,{},{featureElement:a,isEventComplete:function(){return a.find("li.shoveler-cell.shoveler-progress").size()===0}},d))};s({action:"view",page:r.getCurrentPage()+1});a.find(".back-button").click(function(){s({action:"shovel_left",page:r.getCurrentPage()+1})});a.find(".next-button").click(function(){s({action:"shovel_right",
page:r.getCurrentPage()+1})});a.find(".start-over-link").mousedown(function(){s({action:"start_over",page:1,meta:{op:r.getCurrentPage()+1}})});m=function(){e.eventPending(a)||s({action:"resize",page:r.getCurrentPage()+1,logOnlyOnNew:!0,initialDelay:2E3})}},a=function(a){var d={distanceY:-250,distanceX:0};b(a).find(".p13n-sc-nonAUI-carousel").andSelf().filter(".p13n-sc-nonAUI-carousel").each(function(a,e){i.register(e,function(){l(b(e))},d)})},j=function(){a(g)};j();c.when("p13n-sc-ready").execute("p13n-sc-non-aui-carousel:readyInit",
j);return{init:a}});c.when("p13n-sc-jQuery","p13n-sc-util").execute("p13n-sc-carousel-initialization-setup",function(b,f){f.isAUI()?c.when("a-carousel-framework").register("p13n-sc-carousel-init",function(b){return{init:function(){b.createAll()}}}):c.when("p13n-sc-non-aui-carousel").register("p13n-sc-carousel-init",function(b){return{init:function(c){b.init(c)}}})})})})(function(){var c=window.AmazonUIPageJS||P,b=c.attributeErrors;return b?b("P13NSharedSitewideJS"):c}());