(function(u,x){function p(a){if(a){return a.replace(/^\s+|\s+$/g,"");
}}function y(h,j){if(!h){return{};
}h.m&&h.m.message&&(h=h.m);
var i=j.m||j.message||"",i=h.m&&h.m.message?i+h.m.message:h.m&&h.m.target&&h.m.target.tagName?i+("Error handler invoked by "+h.m.target.tagName+" tag"):h.m?i+h.m:h.message?i+h.message:i+"Unknown error",i={m:i,f:h.f||h.sourceURL||h.fileName||h.filename||h.m&&h.m.target&&h.m.target.src,l:h.l||h.line||h.lineno||h.lineNumber,c:h.c?""+h.c:h.c,s:[],t:u.ue.d(),name:h.name,type:h.type,csm:q+" "+(h.fromOnError?"onerror":"ueLogError")},b,c,a=0,f=0,e;
b=h.stack||(h.err?h.err.stack:"");
i.pageURL=j.pageURL||""+(window.location?window.location.href:"")||"missing";
i.logLevel=j.logLevel||z;
if(c=j.attribution){i.attribution=""+c;
}if(b&&b.split){for(i.csm+=" stack",c=b.split("\n");
a<c.length&&i.s.length<g;
){(b=c[a++])&&i.s.push(p(b));
}}else{for(i.csm+=" callee",c=n(h.args||arguments,"callee"),f=a=0;
c&&a<g;
){e=v,c.skipTrace||(b=c.toString())&&b.substr&&(e=0===f?4*v:e,e=1==f?2*v:e,i.s.push(b.substr(0,e)),f++),c=n(c,"caller"),a++;
}}if(!i.f&&0<i.s.length&&(a=i)&&a.s){var d;
b=0<a.s.length?a.s[0]:"";
c=1<a.s.length?a.s[1]:"";
b&&(d=b.match(r));
d&&3==d.length||!c||(d=c.match(s));
d&&3==d.length&&(a.f=d[1],a.l=d[2]);
}return i;
}function n(a,c){try{return a[c];
}catch(b){}}function w(i,b){if(i){var e=y(i,b);
u.ue.log(e,b.channel||t,{n:1});
try{var d=x.console,f=x.JSON,c="Error logged: ";
if(d){if(f&&f.stringify){try{c+=f.stringify(e);
}catch(a){c+="no info provided; converting to string failed";
}}else{c+=e.m;
}"function"===typeof d.error?d.error(c,e):"function"===typeof d.log&&d.log(c,e);
}}catch(h){}}}function m(a,c){if(a&&!(u.ue_err.ec>u.ue_err.mxe)){u.ue_err.ec++;
u.ue_err.ter.push(a);
c=c||{};
var b=a.logLevel||c.logLevel;
c.logLevel=b;
c.attribution=a.attribution||c.attribution;
b&&b!=z||ue_err.ecf++;
w(a,c);
}}if(!u.ueLogError||u.ueLogError.isStub){var t=u.ue_err_chan||"jserr",z="FATAL",q="v5",g=20,v=256,s=/\(?([^\s]*):(\d+):\d+\)?/,r=/.*@(.*):(\d*)/;
w.skipTrace=1;
y.skipTrace=1;
m.skipTrace=1;
(function(){if(u.ue_err.erl){var a=u.ue_err.erl.length,c,b;
for(c=0;
c<a;
c++){b=u.ue_err.erl[c],w(b.ex,b.info);
}ue_err.erl=[];
}})();
u.ueLogError=m;
}})(ue_csm,window);
(function(aq,V){var aA={};
(function(){function f(j){return j<10?"0"+j:j;
}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(j){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(j){return this.valueOf();
};
}var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,h,a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},b;
function i(j){d.lastIndex=0;
return d.test(j)?'"'+j.replace(d,function(l){var k=a[l];
return typeof k==="string"?k:"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+j+'"';
}function e(o,r){var k,l,n,m,q=c,j,p=r[o];
if(p&&typeof p==="object"&&typeof p.toJSON==="function"){p=p.toJSON(o);
}if(typeof b==="function"){p=b.call(r,o,p);
}switch(typeof p){case"string":return i(p);
case"number":return isFinite(p)?String(p):"null";
case"boolean":case"null":return String(p);
case"object":if(!p){return"null";
}c+=h;
j=[];
if(Object.prototype.toString.apply(p)==="[object Array]"){m=p.length;
for(k=0;
k<m;
k+=1){j[k]=e(k,p)||"null";
}n=j.length===0?"[]":c?"[\n"+c+j.join(",\n"+c)+"\n"+q+"]":"["+j.join(",")+"]";
c=q;
return n;
}if(b&&typeof b==="object"){m=b.length;
for(k=0;
k<m;
k+=1){if(typeof b[k]==="string"){l=b[k];
n=e(l,p);
if(n){j.push(i(l)+(c?": ":":")+n);
}}}}else{for(l in p){if(Object.prototype.hasOwnProperty.call(p,l)){n=e(l,p);
if(n){j.push(i(l)+(c?": ":":")+n);
}}}}n=j.length===0?"{}":c?"{\n"+c+j.join(",\n"+c)+"\n"+q+"}":"{"+j.join(",")+"}";
c=q;
return n;
}}if(typeof aA.stringify!=="function"){aA.stringify=function(k,l,j){var m;
c="";
h="";
if(typeof j==="number"){for(m=0;
m<j;
m+=1){h+=" ";
}}else{if(typeof j==="string"){h=j;
}}b=l;
if(l&&typeof l!=="function"&&(typeof l!=="object"||typeof l.length!=="number")){throw new Error("JSON.stringify");
}return e("",{"":k});
};
}}());
var av=(function(){function b(d,e){if(d==null){return e.push("!n");
}if(typeof d==="number"){return e.push("!"+d);
}if(typeof d==="string"){if(d[d.length-1]=="\\"){return e.push("'"+d.replace(/'/g,"\\'")+"u005C'");
}else{return e.push("'"+d.replace(/'/g,"\\'")+"'");
}}if(typeof d==="boolean"){return e.push(d?"!t":"!f");
}if(d instanceof Array){e.push("*");
for(var f=0;
f<d.length;
f++){b(d[f],e);
}return e.push(")");
}if(typeof d=="object"){e.push("(");
for(var c in d){if(d.hasOwnProperty(c)){e.push(c);
b(d[c],e);
}}return e.push(")");
}return e.push("!n");
}function a(d){var c=[];
b(d,c);
return c.join("");
}return{stringify:a};
})();
var az=aq.ue_qsl||2000,ac=1000,am=function(){},O="",P=(V.JSON&&V.JSON.stringify)||(aA&&aA.stringify),ad=av.stringify,ab="ue_frst_v2",Y=aq.ue||{},ar=aq.uet||am,aw=aq.uet||am,Q=ar("bb",ab,{wb:1}),S="//"+aq.ue_furl+"/1/batch/1/OE/",W=[],ao=[],al=[],aC,Z,U=aq.ue_hpfi===undefined?1000:aq.ue_hpfi,au=aq.ue_lpfi===undefined?10000:aq.ue_lpfi,ae={"scheduled-delivery":1},R=0,ai=(function(){var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.5.0","MSXML2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];
function g(){var i=new XDomainRequest();
i.onerror=am;
i.ontimeout=am;
i.onprogress=am;
i.onload=am;
i.timeout=0;
return i;
}function a(){var i=new XMLHttpRequest();
if(!("withCredentials" in i)){throw O;
}return i;
}function h(){var k;
for(var i=0;
i<b.length&&!k;
i++){try{k=new ActiveXObject(b[i]);
b=[b[i]];
}catch(j){}}return k;
}function e(){if(V.XDomainRequest){return g();
}else{if(V.XMLHttpRequest){return a();
}else{if(V.ActiveXObject){return h();
}}}}function f(m){var k=[],j=m[0]||{};
for(var i=0;
i<m.length;
i++){var l={};
l[m[i].c]=m[i].d;
k.push(l);
}return{rid:(j.r||Y.rid),sid:(j.s||aq.ue_sid),mid:(j.m||aq.ue_mid),sn:(j.sn||aq.ue_sn),reqs:k};
}function c(k){var j=f(k),i=e();
if(!i){throw O;
}i.open("POST",S,true);
if(i.setRequestHeader){i.setRequestHeader("Content-type","text/plain");
}i.send(P(j));
}function d(i){for(var j in i){if(i.hasOwnProperty(j)&&i[j].length){c(i[j]);
}}}return{send:d,buildPOSTBodyLog:f};
})(),an=(function(){var i=":",l="$",o="&",k="=",d=",",e=":",g=":",n=":",c="_";
function f(r){var p={},s;
for(var q=0;
q<r.length;
q++){s=r[q].c;
if(!p[s]){p[s]=[];
}p[s].push(r[q]);
}return p;
}function a(t){var u=[];
for(var s in t){if(t.hasOwnProperty(s)){for(var r=0;
r<t[s].length;
r++){var q=t[s][r],p=encodeURIComponent((q.cs?ad:P)(q.d));
u.push({l:p,t:q.t,p:1,c:s,d:(q.cs?"c":"j")});
}}}return u;
}function j(r,q){var s=az-q,p=(r.l.match(".{1,"+s+"}[^%]{0,2}")||[])[0]||"";
r.l=r.l.substr(p.length);
return p;
}function m(r){for(var q=0;
q<r.length;
q++){var p=new Image();
p.src=r[q];
}}function b(B){var r=f(B),t=B[0]||{},C=(t.r||Y.rid),w=(t.s||aq.ue_sid),p=(t.m||aq.ue_mid),E=(t.sn||aq.ue_sn),D=S+p+i+w+i+C+(E?(i+E):""),u=[],q=D,v=a(r),s,y=l,z;
for(var x=0;
x<v.length;
){z=v[x];
if(s!=z.c){q+=y+z.c+k;
y=o;
s=z.c;
}else{q+=d;
}q+=z.d+g+j(z,q.length)+e+z.t;
if(!z.l){x++;
if(z.p!=1){q+=n+z.p+c+z.p;
for(var A=0;
A<z.p-1;
A++){u[u.length-A-1]+=z.p;
}}}else{q+=n+(z.p++)+c;
u.push(q);
q=D;
y=l;
s=0;
}}u.push(q);
m(u);
}function h(q){for(var p in q){if(q.hasOwnProperty(p)){b(q[p]);
}}}return{send:h};
})(),aj=(function(){function a(d){var c=ai.buildPOSTBodyLog(d);
if(!navigator.sendBeacon(S,P(c))){throw O;
}}function b(d){if(!navigator.sendBeacon){throw O;
}for(var c in d){if(d.hasOwnProperty(c)){a(d[c]);
}}}return{send:b};
})();
function ap(e){var a={},b,c;
for(var d=0;
d<e.length;
d++){c=e[d];
b=c.r+c.s+c.m;
if(!c.c){continue;
}if(!a[b]){a[b]=[];
}a[b].push(e[d]);
}return a;
}function ag(c){for(var b=1;
b<arguments.length;
b++){try{return arguments[b].send(c);
}catch(a){}}}function at(){for(var a=0;
a<al.length;
a++){al[a]();
}if(W.length){ag(ap(W.splice(0,W.length)),aj,ai,an);
}Z=0;
aC=0;
}function aB(){if(U===0){at();
}else{if(!aC){aC=V.setTimeout(at,U);
}}}function ak(){if(!Z){Z=V.setTimeout(at,au);
}}function ay(a,b,d){d=d||{};
var c={r:d.r||Y.rid,s:d.s||aq.ue_sid,m:d.m||aq.ue_mid,sn:d.sn||aq.ue_sn,c:b,d:a,t:(d.t||Y.d()),cs:d.c&&aq.ue_qsl};
if(d.b){ag(ap([c]),aj,an);
}else{if(d.img||ae[b]){ag(ap([c]),an);
}else{if(d.n){W.push(c);
aB();
}else{W.push(c);
ak();
}}}}function ah(a,b,c){R++;
if(R==ac){ay({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},V.ue_err_chan||"jserr");
}else{if(R<ac){ay(a,b,c);
}}}function ax(){if(!Y.log||!Y.log.isStub){return;
}Y.log.replay(function(c,a,b){var d=c[2]||{};
ah(c[0],c[1],{m:d.m,s:d.s,sn:d.sn,t:a,r:b,n:1});
});
Y.onunload.replay(function(a){ao.push(a[0]);
});
Y.onflush.replay(function(a){al.push(a[0]);
});
}function T(){for(var a=0;
a<ao.length;
a++){ao[a]();
}ag(ap(W.splice(0,W.length)),aj,an);
}function aa(a){ao.push(a);
}function af(a){al.push(a);
}function X(){R=0;
}Y._fic=an;
Y._fac=ai;
Y._fbc=aj;
Y._flq=W;
Y.sid=aq.ue_sid;
Y.mid=aq.ue_mid;
Y.furl=aq.ue_furl;
Y.sn=aq.ue_sn;
if(V.amznJQ&&V.amznJQ.declareAvailable){V.amznJQ.declareAvailable("forester-client");
}if(V.P&&V.P.register){V.P.register("forester-client",am);
}ax();
Y.log=ah;
Y.log.reset=X;
Y.onunload=aa;
Y.onflush=af;
Y.attach("beforeunload",T);
aw("ld",ab,{wb:1});
})(ue_csm,window);
(function(c,d){if(c.ue_cel){return;
}c.ue_cel=(function(){var b=600000,y=[],w=[],C="csmCELLSframework",z="cel",v,a=c.ue,A=c.uet,D=c.uex,B=a.rid,s=d.requestAnimationFrame||function(e){e();
};
function t(){var f=d.performance||d.webkitPerformance,g=f&&f.navigation&&f.navigation.type==2,h=document.ue_backdetect&&document.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,e=a.bfini;
if(g||(e&&(e>1))||(!e&&h&&(h>1))){return 1;
}return 0;
}function x(e,f){if(f){f.r=B;
}else{f={r:B,c:1};
}if(f.clog&&a.clog){a.clog(e,z,f);
}else{a.log(e,z,f);
}}a.isBF=t();
if(a.isBF){x({k:"bft",t:a.d()});
return;
}if(typeof A=="function"){A("bb",C,{wb:1});
}function u(){var h=y.length;
if(h>0){var g=[];
for(var e=0;
e<h;
e++){var f=y[e].api;
if(f.ready()){f.on({ts:a.d,ns:z});
w.push(y[e]);
x({k:"mso",n:y[e].name,t:a.d()});
}else{g.push(y[e]);
}}y=g;
}}setTimeout(u,0);
function r(){if(!r.executed){for(var e=0;
e<w.length;
e++){if(w[e].api.off){w[e].api.off({ts:a.d,ns:z});
}}x({k:"eod",t0:a.t0,t:a.d()},{c:1});
r.executed=1;
for(var f=0;
f<w.length;
f++){y.push(w[f]);
}w=[];
clearTimeout(v);
}}a.onunload(r);
v=setTimeout(r,b);
if(typeof D=="function"){D("ld",C,{wb:1});
}return{registerModule:function(f,e){y.push({name:f,api:e});
x({k:"mrg",n:f,t:a.d()});
u();
},reset:function(f){x({k:"rst",t0:a.t0,t:a.d()});
B=f||a.rid;
y=y.concat(w);
w=[];
var g=y.length;
for(var e=0;
e<g;
e++){y[e].api.off();
y[e].api.reset();
}u();
clearTimeout(v);
v=setTimeout(r,b);
r.executed=0;
},timeout:function(e,f){return d.setTimeout(function(){s(e);
},f);
},log:x};
})();
})(ue_csm,window);
(function(e,f,d){if(e.ue_pdm){return;
}if(ue.isBF){return;
}e.ue_pdm=(function(){var G,H,b,u,x,z,C="csmCELLSpdm",A,w=0,c=0,a=e.ue,y=e.ue_cel.log,B=e.uet,D=e.uex;
if(typeof B=="function"){B("bb",C,{wb:1});
}function E(){var g={w:G.width,aw:G.availWidth,h:G.height,ah:G.availHeight,cd:G.colorDepth,pd:G.pixelDepth};
var h={w:d.body.scrollWidth,h:d.body.scrollHeight};
if(!x||x.w!=g.w||x.h!=g.h||x.aw!=g.aw||x.ah!=g.ah||x.pd!=g.pd||x.cd!=g.cd){x=g;
x.t=b();
x.k="sci";
y(x);
}if(!z||z.w!=h.w||z.h!=h.h){z=h;
z.t=b();
z.k="doi";
y(z);
}H=e.ue_cel.timeout(E,u);
}function F(){y({k:"ebl",t:b()});
}function v(){y({k:"efo",t:b()});
}return{on:function(g){u=g.timespan||500;
b=g.ts;
A=g.ns;
G=f.screen;
if(a.attach){a.attach("blur",F,f);
a.attach("focus",v,f);
}e.ue_cel.timeout(E,0);
if(typeof D=="function"){D("ld",C,{wb:1});
}},off:function(g){clearTimeout(H);
if(a.detach){a.detach("blur",F,f);
a.detach("focus",v,f);
}if(a.count){a.count("cel.PDM.TotalExecutions",c);
a.count("cel.PDM.TotalExecutionTime",w);
a.count("cel.PDM.AverageExecutionTime",w/c);
}},ready:function(){return d.body&&e.ue_cel&&e.ue_cel.log;
},reset:function(){z=null;
x=null;
}};
})();
if(e.ue_cel){e.ue_cel.registerModule("page module",e.ue_pdm);
}})(ue_csm,window,document);
(function(d,c){if(d.ue_vpm){return;
}if(ue.isBF){return;
}d.ue_vpm=(function(){var F,L,H,x,I="csmCELLSvpm",G,w=0,a=0,A=d.ue,J=d.ue_cel.log,C=d.uet,E=d.uex,z=A.attach,v=A.detach,B=d.ue_ueh;
if(typeof C=="function"){C("bb",I,{wb:1});
}function K(){var e=x(),f={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};
if(!F||F.w!=f.w||F.h!=f.h||F.x!=f.x||F.y!=f.y){f.t=e;
f.k="vpi";
F=f;
J(F,{clog:1});
}if(B){L=0;
}else{L=d.ue_cel.timeout(K,H);
}w=x()-e;
a+=1;
}function D(){if(L){return;
}L=d.ue_cel.timeout(K,H);
}function y(){if(z){z("scroll",D);
z("resize",D);
}}function b(){if(v){v("scroll",D);
v("resize",D);
}}return{on:function(e){x=e.ts;
G=e.ns;
H=e.timespan||100;
d.ue_cel.timeout(K,0);
if(B){y();
}if(typeof E=="function"){E("ld",I,{wb:1});
}},off:function(e){clearTimeout(L);
if(B){b();
}if(A.count){A.count("cel.VPI.TotalExecutions",a);
A.count("cel.VPI.TotalExecutionTime",w);
A.count("cel.VPI.AverageExecutionTime",w/a);
}},ready:function(){return d.ue_cel&&d.ue_cel.log;
},reset:function(){F=undefined;
},getVpi:function(){return F;
}};
})();
if(d.ue_cel){d.ue_cel.registerModule("viewport module",d.ue_vpm);
}})(ue_csm,window);
(function(j,h,i){var f=j.ue||{};
function g(){return !f.isBF&&!j.ue_fem&&i.querySelector&&h.getComputedStyle&&[].forEach;
}if(!g()){return;
}j.ue_fem=(function(){var ad=50,b=10,aF=3000,aa,ar="csmCELLSfem",aG=[],Z=function(){},ae=[],az=j.ue_cel.log,al,av,au,c,ak=h.MutationObserver||h.WebKitMutationObserver||h.MozMutationObserver,aC=!!ak,W,aw,d="DOMAttrModified",an="DOMNodeInserted",Y="DOMNodeRemoved",e,ab,ap=-aF;
if(typeof uet=="function"){uet("bb",ar,{wb:1});
}function aA(){j.ue_cel.timeout(function(){ae.splice(0).forEach(function(k){az(k,{clog:1});
});
},0);
}function ao(k,l){ae.push({n:k.cel_n,t:l,k:"ewd"});
}function a(k,l){ae.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:l,k:"ewi",cl:k.className});
}function ay(k,l){ae.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:l,k:"ewi"});
}function at(l){var o={x:h.pageXOffset,y:h.pageYOffset};
for(var p=0;
p<aG.length;
p++){var k=aG[p];
if(!k.w||!k.w.length){continue;
}for(var n=0;
n<k.w.length;
n++){var m=k.w[n],q=aD(m,o);
if(q&&!m.cel_b){m.cel_b=q;
a(m,l);
}else{if(q&&ac(m.cel_b,q)){m.cel_b=q;
ay(m,l);
}}}}}function aH(k){if(k.c){return i.getElementsByClassName(k.c);
}if(k.id){return[i.getElementById(k.id)];
}return i.querySelectorAll(k.s);
}function ah(l){for(var r=0;
r<aG.length;
r++){var k=aG[r],q=aH(k),n=(k.w||[]),p;
for(p=0;
p<n.length;
p++){var m=n[p];
if(!al.contains(m)){ao(m,l);
}}k.w=[];
for(p=0;
p<q.length;
p++){var o=q[p];
if(!o){continue;
}if(!o.cel_n){o.cel_n=o.getAttribute("cel_widget_id")||(k.id_gen||Z)(o,p)||o.id;
}k.w.push(o);
}}aI();
}function aD(l,m){try{return aj(l,m);
}catch(k){}}function aj(l,m){if(!l){return;
}var k=l.getBoundingClientRect();
return{x:(k.left+m.x)|0,y:(k.top+m.y)|0,w:k.width|0,h:k.height|0,d:(l.offsetWidth===0&&l.offsetHeight===0)|0};
}function aq(l,k){if(l>k){return l-k<3;
}else{return k-l<3;
}}function ac(l,k){return !(aq(l.x,k.x)&&aq(l.y,k.y)&&aq(l.w,k.w)&&aq(l.h,k.h)&&(l.d===k.d));
}function aE(){if(!ab){ab=j.ue_cel.timeout(function(){ab=null;
ai("dwe",ah);
aA();
},ad);
}}function aI(){if(!ab&&!e){e=j.ue_cel.timeout(function(){e=null;
ai("dwpc",at);
aA();
},ad);
}}function ax(l,k){if(l<=b){return 0;
}if((k-ap)>=aF){ap=k;
return 0;
}ue_fem.off();
return 1;
}function ai(p,l){var n=aa();
l(n);
var k=aa(),m=k-n,o=ax(m,k);
if(ae.length||o){ae.push({k:"ewt",e:p,d:m,ex:o,t:aa()});
}}function ag(){var l={attributes:true,subtree:true},k={childList:true};
W=new ak(aI);
aw=new ak(aE);
W.observe(al,l);
aw.observe(al,k);
aw.observe(av,l);
}function af(){au.call(al,d,aI);
au.call(al,an,aE);
au.call(al,Y,aE);
au.call(av,an,aI);
au.call(av,Y,aI);
}function X(){if(aC){ag();
}else{af();
}}function aB(){if(aw){aw.disconnect();
aw=null;
}if(W){W.disconnect();
W=null;
}c.call(al,d,aI);
c.call(al,an,aE);
c.call(al,Y,aE);
c.call(av,an,aI);
c.call(av,Y,aI);
}function am(){return au&&c&&al&&al.contains&&al.getBoundingClientRect&&aa;
}return{on:function(k){al=i.body;
av=i.head;
au=al.addEventListener;
c=al.removeEventListener;
aa=k.ts;
aG=j.cel_widgets||[];
function l(){if(am()){X();
aE();
}}if(f.deffered){l();
}else{if(f.attach){f.attach("load",l);
}}if(typeof uex=="function"){uex("ld",ar,{wb:1});
}},off:function(){if(am()){aB();
}},ready:function(){return j.ue_cel&&j.ue_cel.log;
},reset:function(){aG=j.cel_widgets||[];
}};
})();
if(j.ue_cel&&j.ue_fem){j.ue_cel.registerModule("features module",j.ue_fem);
}})(ue_csm,window,document);
